# Generated by Django 5.0.2 on 2024-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('round', models.SmallIntegerField()),
                ('number', models.SmallIntegerField()),
                ('points', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('double_or_nothing', models.BooleanField(default=False)),
                ('answer1', models.CharField(max_length=200, null=True)),
                ('answer2', models.CharField(max_length=200, null=True)),
                ('answer3', models.CharField(max_length=200, null=True)),
                ('answer4', models.CharField(max_length=200, null=True)),
                ('answer5', models.CharField(max_length=200, null=True)),
                ('answer6', models.CharField(max_length=200, null=True)),
                ('answer7', models.CharField(max_length=200, null=True)),
                ('answer8', models.CharField(max_length=200, null=True)),
                ('answer9', models.CharField(max_length=200, null=True)),
                ('answer10', models.CharField(max_length=200, null=True)),
                ('round', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('round_one_points', models.SmallIntegerField(default=0)),
                ('round_two_points', models.SmallIntegerField(default=0)),
                ('round_three_points', models.SmallIntegerField(default=0)),
                ('round_four_points', models.SmallIntegerField(default=0)),
                ('round_five_points', models.SmallIntegerField(default=0)),
                ('round_six_points', models.SmallIntegerField(default=0)),
                ('round_seven_points', models.SmallIntegerField(default=0)),
                ('total_points', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
    ]
