# Generated by Django 5.0.2 on 2024-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('visible', models.BooleanField(default=False)),
                ('date_used', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='round_five_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='round_seven_points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='round_six_points',
        ),
    ]
