# Generated by Django 5.0.2 on 2024-02-18 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_round_remove_team_round_five_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-date_used']},
        ),
        migrations.AddField(
            model_name='round',
            name='answers_visible',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rounds.round'),
        ),
    ]
