# Generated by Django 5.0.2 on 2024-02-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0004_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
