# Generated by Django 5.0.2 on 2024-02-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0005_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='answers_visible',
        ),
        migrations.AddField(
            model_name='round',
            name='answers',
            field=models.TextField(null=True),
        ),
    ]
