# Generated by Django 5.0.2 on 2024-02-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0007_alter_round_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='team_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='rounds.team'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.SmallIntegerField(default=1),
        ),
    ]
