# Generated by Django 5.0.2 on 2024-02-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0008_submission_team_object_alter_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='team_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='rounds.team'),
        ),
    ]
