# Generated by Django 5.0.2 on 2024-02-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0009_alter_submission_team_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
