version: "3.7"
services:
  trivia:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  react:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./ghi/trivia:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
